[package]
name = "undo"
version = "0.8.1"
authors = ["evenorog <evenorog@gmail.com>"]
description = "An undo/redo library with dynamic dispatch, state handling and automatic command merging."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT"
keywords = ["undo", "redo"]

[dependencies]
fnv = "1.0.5"
