[package]
name = "undo"
version = "0.42.3"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Low-level undo-redo functionality."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo", "command", "record", "history"]
categories = ["data-structures", "rust-patterns", "no-std"]
exclude = ["/.travis.yml"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", optional = true, features = ["serde"] }
colored = { version = "2", optional = true }
serde = { version = "1", optional = true, default-features = false, features = ["derive"] }
arrayvec = { version = "0.5", default-features = false, features = ["serde"] }

[features]
default = ["alloc"]
alloc = ["serde/alloc"]

[badges]
travis-ci = { repository = "evenorog/undo" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["chrono", "colored", "serde"]
