[package]
name = "undo"
version = "0.28.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "An undo-redo library with dynamic dispatch and automatic command merging."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures"]

[dependencies]
bitflags = { version = "1", optional = true }
chrono = { version = "0.4.6", optional = true }
colored = { version = "1", optional = true }
rustc-hash = "1"

[features]
default = []
display = ["bitflags", "colored"]

[badges]
travis-ci = { repository = "evenorog/undo" }
maintenance = { status = "actively-developed" }
