[package]
name = "undo"
version = "0.43.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Low-level undo-redo functionality."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo", "command", "record", "history"]
categories = ["data-structures", "rust-patterns", "no-std"]
exclude = ["/.travis.yml"]
edition = "2018"

[dependencies]
arrayvec = { version = "0.7", optional = true, default-features = false }
chrono = { version = "0.4", optional = true }
colored = { version = "2", optional = true }
serde_crate = { package = "serde", version = "1", optional = true, default-features = false, features = ["derive"] }

[features]
default = ["alloc", "arrayvec"]
alloc = ["serde_crate/alloc"]
serde = ["serde_crate", "chrono/serde", "arrayvec/serde"]

[badges]
travis-ci = { repository = "evenorog/undo" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["chrono", "colored", "serde"]
