[package]
name = "undo"
version = "0.5.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "An undo/redo library with state awareness and automatic command merging."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT"
keywords = ["undo", "redo"]

[dependencies]
fnv = "1.0.5"
