[package]
name = "undo"
version = "0.17.3"
authors = ["evenorog <evenorog@gmail.com>"]
description = "An undo-redo library with dynamic dispatch and automatic command merging."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures"]

[dependencies]
