[package]
name = "undo"
version = "0.36.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides undo-redo functionality with dynamic dispatch and automatic command merging."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures", "rust-patterns"]
exclude = ["/.travis.yml", "/undo.svg"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.9", optional = true }
colored = { version = "1", optional = true }
rustc-hash = "1"

[features]
default = []
display = ["colored"]

[badges]
travis-ci = { repository = "evenorog/undo" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["chrono", "display"]
