[package]
name = "undo"
version = "0.41.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides simple undo-redo functionality with dynamic dispatch."
documentation = "https://docs.rs/undo"
repository = "https://github.com/evenorog/undo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo"]
categories = ["data-structures", "rust-patterns"]
exclude = ["/.travis.yml"]
edition = "2018"

[dependencies]
chrono = "0.4"
colored = "2"

[badges]
travis-ci = { repository = "evenorog/undo" }
maintenance = { status = "actively-developed" }
